### ISSUE TITLE
With v2.2.1 I can no longer use ES6 let

### ISSUE THREAD

**Issue by AddictArts** [princejwesley/Mancy#100]
let a = [ 1, 2, 3 ]
ES5(transpiled)let a = [
  1,
  2,
  3
];
SyntaxError:  Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

I tried strict, magic, and sloppy. No luck, I get the same error.

**Comment by princejwesley** [comment]
@AddictArts Fixed.

**Comment by AddictArts** [comment]
Thanks for the quick fix, running the latest from master
