### ISSUE TITLE
How to use Mancy console to learn "selenium-webdriver" ?

### ISSUE THREAD

**Issue by Goster** [princejwesley/Mancy#101]
I want to learn "selenium-webdriver" using Mancy so I:
1. downloaded appropriate module into path "A":
cd A
npm install selenium-webdriver
2. next I saved path "A" in Mancy properties as modules path
3. I try to run following code:
```javascript
var webdriver = require('selenium-webdriver'),
	By = require('selenium-webdriver').By,
    until = require('selenium-webdriver').until,
    chrome = require('selenium-webdriver/chrome');

var options = new chrome.Options();
options.setChromeBinaryPath("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");	

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .build();
	
driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```
This code runs perfectly when I use node directly (node version -> v5.7.0) but when I run it in Mancy then I get error: "TypeError: capabilities.merge is not a function". I see that Mancy uses node version  v5.1.1. Wheter it is causing the error ? What I should to do to eliminate this error ?

**Comment by princejwesley** [comment]
@Goster I could able to run with the below code (even though, I am getting runtime error saying `cant find irct 'desiredCapabilities'`).
![image](https://cloud.githubusercontent.com/assets/1622515/13374500/4a6edf0a-ddac-11e5-9572-33360c159a14.png)

**Comment by princejwesley** [comment]
@Goster Add 'A/node_modules' as path

**Comment by princejwesley** [comment]
@Goster Fixed. Build mancy from source (`master` branch)
![image](https://cloud.githubusercontent.com/assets/1622515/13374907/96c39a8e-ddb7-11e5-95b3-f3556a349220.png)

**Comment by Goster** [comment]
thx for quick response ;-)

> Build mancy from source (master branch)

I did (I didn't see errors during the whole process):
Clone and run npm install & npm run package
and now Mancy starts but window is empty ;-( : 
![screenshot - 2016-02-29 13_32_33](https://cloud.githubusercontent.com/assets/16000763/13394523/47d71e36-dee9-11e5-94fe-2a7d61e609ce.png)

BTW: thx for great software ! ;-) I see a lot of potential in Mancy

**Comment by princejwesley** [comment]
@Goster Try `npm run debug` or `gulp debug`. Once app is up, select `view > Toggle Developer Tools` and paste the console error here.

**Comment by princejwesley** [comment]
@Goster I remember, I faced `electron-rebuild` related issue while building exe in windows. Try [this suggestion](https://github.com/electronjs/electron-rebuild/issues/39#issuecomment-165128082)

**Comment by Goster** [comment]
> Try npm run debug or gulp debug

cd Mancy\resources\app
npm run debug
_[13:30:08] No gulpfile found_

> Try this suggestion

I can't find file spawn.js in Mancy directory

**Comment by princejwesley** [comment]
@Goster Pull the latest code and run `npm install` and `npm run package`

**Comment by Goster** [comment]
Now it works!! thx!

Last question: is it normal situation that when I run following code (which has a bug inside -> wrong path to exe file):
```javascript
var webdriver = require('selenium-webdriver'),
	By = require('selenium-webdriver').By,
    until = require('selenium-webdriver').until,
    chrome = require('selenium-webdriver/chrome');

var options = new chrome.Options();
options.setChromeBinaryPath("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chromeeeeeeeeee.exe");	

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .build();
```
then I don't see any error on console unless I do something like this:
```javascript
process.on('uncaughtException', (err) => {
  console.error(`Caught exception: ${err}`);
});
```

?

**Comment by princejwesley** [comment]
@Goster Any errors should be displayed. I'll look into that. Can you raise new bug or I'll do?

**Comment by Goster** [comment]
> Can you raise new bug or I'll do?

no problem ;-)
