### ISSUE TITLE
Cannot use console.log in TypeScript mode

### ISSUE THREAD

**Issue by wenLiangcan** [princejwesley/Mancy#102]
![selection_009](https://cloud.githubusercontent.com/assets/1244181/13378236/49cd2b50-de39-11e5-9a8f-e47efcc2ca2b.png)

**Comment by princejwesley** [comment]
@wenLiangcan Use `global.console` as  work around.

**Comment by wenLiangcan** [comment]
Thank you, that worked!

**Comment by princejwesley** [comment]
@wenLiangcan Fix is available in master branch

**Comment by wenLiangcan** [comment]
Thanks @princejwesley

**Comment by princejwesley** [comment]
@wenLiangcan welcome :smile:

**Comment by dougajmcdonald** [comment]
or `window.console`
