### ISSUE TITLE
Open Mancy as management for specific node.js app

### ISSUE THREAD

**Issue by timnew** [princejwesley/Mancy#105]
I have looking for solution in node.js world as Rails Console in Ruby on Rails world.

In some time, we might want to do some temporary diagnosis or management task for node app(such as express web server that connected to db/redis other resources)

In this scenario, I want to run some snippet based on my app logic.
Such as instantiating a business model with some hand-writing values and then saving it into database.

I tried to do it in node.js REPL, but so far, it isn't a fancy experience at all.
Then I found Mancy could be an excellent candidate for this kind of scenario.

The only requirement is that I can require modules and files from specific folder, and start mancy from terminal:

e.g.

I wish to launch Mancy in this way:
```shell
> mancy path/to/my/cool/app
```
After Mancy started, I wish to run following code:
```js
require('./initEnv')
import User from './models/User'

await User.forge({ username: 'timnew', password: 'aSecretNoOneKnows '}).save()
```

**Comment by princejwesley** [comment]
@timnew Added path support from process argument. Use  `mancy -p path`

```
Usage: mancy [options]

Options:
  -d, --debug     Run in debug mode  [boolean]
  -e, --editor    REPL or Notebook(experimental) mode.
                  Allowed values:
                    'repl', 'notebook'

  -j, --js-flags  js flags for nodejs.
  -l, --lang      Scripting language.
                  Allowed values:
                    'js', 'javascript', 'babel'
                    'ts', 'typescript'
                    'ls', 'livescript'
                    'coffee', 'coffeescript'

  -m, --mode      REPL mode (applicable only for --lang=js).
                  Allowed values:
                    'magic', 'sloppy' or 'strict'

  -p, --path      Add npm path(s) with path delimiter
  -s, --script    Start up script file to load.
  -t, --theme     Editor theme.
                  Allowed values:
                    dark', 'light'

  -h, --help      Show help  [boolean]

```

**Comment by mcendon** [comment]
It doesnt work

**Comment by princejwesley** [comment]
@mcendon Which command line option is not working? I'll try to set up and test it.

**Comment by mcendon** [comment]
Hi, no one is working... i've try -h, --help, --debug, and others and nothing happens, only the mancy gui is showed... 
I always get the same behavior in all cases

Maybe you can try with the --help or -h command option first to test it

**Comment by princejwesley** [comment]
@mcendon Very sorry. I'll fix this issue.

Here is an ugly work around: (ignore the first option)
```
$ mancy . --help
$ mancy . -h
```

**Comment by princejwesley** [comment]
@mcendon Try `npm` version: `3.0.0-1`. Fixed [here](https://github.com/princejwesley/npm-mancy/commit/38f2718180122d84be47257965c26380ddd729ee)

**Comment by mcendon** [comment]
@princejwesley thank you!!! , it works now :)

can you please see this? https://github.com/princejwesley/Mancy/issues/124
