### ISSUE TITLE
really really needs bracket matching.

### ISSUE THREAD

**Issue by georgejecook** [princejwesley/Mancy#106]
would be great to get highlighting for brackets, so you can see which ( or { you are closing when you type ( or }

**Comment by princejwesley** [comment]
Time to refactor and use real code editor.

**Comment by georgejecook** [comment]
I concede that's the case; but look at this
`User.findAll({where:{lastName:'cook'}}).then(function (users){users.map (function (u){console.log(u.lastName)})})`

I don't think that's really _that_ big.. but it's a pita to write without some kind of bracket help. I'll look into adding it in a week or two; but if you know how to do it, you really should - it would help a lot. Great REPL btw - very promising! :)

**Comment by princejwesley** [comment]
@georgejecook @pmros suggested to use real editor like code mirror. Integrating code mirror saves time and we no need to test and maintain editor specific code. Every time adding new feature with limited testing is not a good sign :smile:

**Comment by princejwesley** [comment]
Code mirror is integrated to master. Keeping this ticket open until master branch is stable.

**Comment by antonyr** [comment]
:+1:
