### ISSUE TITLE
Click on prompt (">")

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#11]
When you click on prompt (">"), it only changes its orientation. Tooltip says "expand command", should it work like minimize/maximize buttom?

**Comment by princejwesley** [comment]
Yes for multiple line commands.

![before](https://cloud.githubusercontent.com/assets/1622515/10537418/4bf77d0c-740f-11e5-8e15-45e2f2483324.png)

Collapsed:
![after](https://cloud.githubusercontent.com/assets/1622515/10537419/4eaa7234-740f-11e5-8714-6a4fecb537bf.png)
