### ISSUE TITLE
Similar to issue #83 with fix

### ISSUE THREAD

**Issue by WolfieWerewolf** [princejwesley/Mancy#110]
Hey... just thought I would let you know that I just cloned this and when I attempted to npm install I was also getting errors from node-gyp related to font-manager.  I'm on OSX 10.11 (all updates) and at this time the version of Electron-prebuilt it's pulling down is 0.37.2.  I checked the NPM status of font-manager and noticed that their current version is 0.2.2 and the provided package.json was requesting 0.2.0.  I updated this and the npm install worked fine... Just thought I would share this in case others experience the same issue.  Great project BTW!  Keep up the good work.

/W

**Comment by princejwesley** [comment]
@WolfieWerewolf , I am aware of that and I have a fix in my `clojurescript` branch. I'll merge it to master in few days.

In fact, I raised a ticket [there](https://github.com/devongovett/font-manager/pull/5) :)

**Comment by WolfieWerewolf** [comment]
Awesome.. please feel free to close this as it wasn't really an issue anyway.. I didn't look at any of the other branches.. I typically just clone the master recursively.  Again, great stuff!

Thanks

**Comment by princejwesley** [comment]
@WolfieWerewolf I'll keep it open until I merge `clojurescript` branch to master

**Comment by princejwesley** [comment]
Merged font-manger version upgrade changes to master.
