### ISSUE TITLE
Focus on prompt line

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#12]
If you click, for example, a minimize buttom, you lose focus on prompt line. So you have to click on prompt line to write again. I think prompt line should be focus all the time or mostly. Click an empty space of main panel, should focus prompt line. Maybe keypress event too.
These are only suggestions. I hope they help you. Mancy is great!

**Comment by princejwesley** [comment]
Thanks. I'll incorporate it in version 2. Some of your suggestions are already done but are not ready for release. Wait for 3 weeks :smile:

**Comment by pmros** [comment]
I've tried v2 branch and looks good!

**Comment by georgejecook** [comment]
I tried it on version 2 and it still loses focus all the time

![screen shot 2016-03-04 at 8 52 25 pm](https://cloud.githubusercontent.com/assets/1214545/13544897/1aef2b9c-e24b-11e5-8572-beaf47ab6245.png)

**Comment by princejwesley** [comment]
@georgejecook Yes. We can track focus issue here.

**Comment by georgejecook** [comment]
yes. sorry about the dupe.

**Comment by princejwesley** [comment]
@georgejecook No problem :smile:

**Comment by princejwesley** [comment]
Only feasible solution is to make sure to focus active prompt
 - After every command execution
 - on window getting focus
 - Missed something!!! :microscope: 

Focusing when
 - clicking off the prompt (_selecting data from main area is impossible if we keep the focus off_ ) 
 - minimise/close command output (_if we have sufficient data in main window, every minimise/close action scrolls window down to active prompt_)

are invalid

**Comment by Kikobeats** [comment]
Currently the window lose the prompt cursor all the time:

![test](https://cloud.githubusercontent.com/assets/2096101/14615627/d79d8b2a-05a6-11e6-9376-cc33dc232ab7.gif)

specially in the new notebook mode!
