### ISSUE TITLE
Add module path doesn't work

### ISSUE THREAD

**Issue by beppu** [princejwesley/Mancy#120]
When you try to add a new module path, it crashes, because it's trying to call `forEach` on an object called `langs`.

https://github.com/princejwesley/Mancy/blob/master/src/languages/ReplLanguages.js#L71

Mancy v3.0.0 OSX

**Comment by princejwesley** [comment]
This issue affects `clojurescript` mode.

**Comment by princejwesley** [comment]
Fix is merged to master.
