### ISSUE TITLE
Please add a --session option to load a session from command line

### ISSUE THREAD

**Issue by mcendon** [princejwesley/Mancy#124]
Hi, I have a program that exports a mancy's session file and I want to load it from command line.

I've tried with the --script option but it was made to load a .js

Please add a --session option (or similar) to load a session from command line

**Comment by princejwesley** [comment]
Sure. I'll do and let you know

**Comment by mcendon** [comment]
Thanks!!!!! :100:

**Comment by mcendon** [comment]
Hi @princejwesley, do you already have an aprox date for the next release?

**Comment by princejwesley** [comment]
@mcendon End of this month! (I'll fix open tickets and release it)

**Comment by mcendon** [comment]
@princejwesley Great! thanks!

**Comment by mcendon** [comment]
any update? @princejwesley

**Comment by princejwesley** [comment]
@mcendon Very sorry 😞 . I'll build binaries and release this week end. I'll inform you once done.

**Comment by princejwesley** [comment]
@mcendon Released!

**Comment by mcendon** [comment]
@princejwesley im having the following problem

mauro@mauro-pc:~/Downloads/Mancy-linux-x64$ npm install -g mancy@3.1.0
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/mauro/.nvm/versions/node/v4.3.1/bin/node" "/home/mauro/.nvm/versions/node/v4.3.1/bin/npm" "install" "-g" "mancy@3.1.0"
npm ERR! node v4.3.1
npm ERR! npm  v3.10.5

npm ERR! No compatible version found: mancy@3.1.0
npm ERR! Valid install targets:
npm ERR! 3.0.0, 3.0.0-1, 2.2.2, 2.2.1, 2.2.0, 2.2.0-2, 2.2.0-1, 2.1.0, 2.1.0-1, 2.0.1, 2.0.0, 1.0.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mauro/Downloads/Mancy-linux-x64/npm-debug.log


mauro@mauro-pc:~/Downloads/Mancy-linux-x64$ node --version
v4.3.1
mauro@mauro-pc:~/Downloads/Mancy-linux-x64$ npm --version
3.10.5
mauro@mauro-pc:~/Downloads/Mancy-linux-x64$

**Comment by princejwesley** [comment]
@mcendon Sorry! Try now!
