### ISSUE TITLE
Compat table

### ISSUE THREAD

**Issue by AutoSponge** [princejwesley/Mancy#13]
I think it would be helpful to see, at a glance, what language features are supported in the REPL. Maybe as an added feature have the ability to toggle available features.

**Comment by princejwesley** [comment]
@AutoSponge  Do we need to disable available features?

BTW, version 2(available in 3 weeks) has support to enable/disable babel integration.

**Comment by jfsiii** [comment]
@princejwesley Sorry if this is off-topic, but is the babel integration a single toggle? 

It'd be great to enable all features >= a given stage or (stretch goal) [individual features](https://github.com/tc39/ecma262/#current-proposals) (e.g. Array.prototype.includes)

**Comment by princejwesley** [comment]
@jfsiii No, its not a single toggle, we can configure babel options in preference window. what is your recommentation?

**Comment by AutoSponge** [comment]
@princejwesley I'm with @jfsiii, `Array#includes` is one of those polyfills that's not included by default but I use it all the time. I wonder if the entire .babelrc should be under user control with some ability to swap between common combinations.

**Comment by princejwesley** [comment]
:+1:

**Comment by princejwesley** [comment]
Merged to master
