### ISSUE TITLE
Types on typescript are not respected

### ISSUE THREAD

**Issue by nschurmann** [princejwesley/Mancy#133]
when i write:
```typescript
const a = (x: number) => x + 2
a("hello") // returns "hello2"
```

This should throw an error.

**Comment by princejwesley** [comment]
@nschurmann  Turn off   `Preferences > Compiler Options > Ignore Semantic Errors`
![image](https://cloud.githubusercontent.com/assets/1622515/15970169/faf119ba-2f50-11e6-8ce4-6fff94d85d3b.png)

**Comment by nschurmann** [comment]
lol, thanks @princejwesley
