### ISSUE TITLE
How does require work?

### ISSUE THREAD

**Issue by kucukkanat** [princejwesley/Mancy#134]
When i type 
```
var x = require("something")
```
there is a loading icon spins around as I guess it downloads the package from npm. But where does Mancy exactly download the package in my PC. Does anybody have an idea ? 
Tried hard but couldn't find a clue.

**Comment by princejwesley** [comment]
###### Automatic download path

Platform | Download Path
------------ | -------------------
Windows | C:\Users\%USERNAME%\AppData\Local\mancy\node_modules
OS X | ~/Library/Application Support/mancy/node_modules
Linux | ~/.config/mancy/node_modules

**Comment by kucukkanat** [comment]
Awesome quick response! Thanks for it.
One quick and last question about modules:
When I File>Add Module Path , is it only for the app session or does it keep when I close and open Mancy back again? How does it actually work ?

**Comment by princejwesley** [comment]
@kucukkanat To persist your configuration, use `Preferences > Add Node Modules Path`
![image](https://cloud.githubusercontent.com/assets/1622515/16047635/7531f65c-326e-11e6-9812-31e26b335b29.png)
