### ISSUE TITLE
  "babel-runtime": "^6.9.1",

### ISSUE THREAD

**Issue by WolfieWerewolf** [princejwesley/Mancy#135]
Dude.. I love this project but you might want to consider deleting your global node_modules folder or something... I have yet to get this thing to build without having to find the missing dependency.  This time you're missing the one above.

:-)

**Comment by princejwesley** [comment]
@WolfieWerewolf It works for me without explicitly adding the above dependency even after deleting global and local modules. Last time, I removed `babel-runtime` dependency to avoid downloading multiple versions of it (It helped to reduce executable memory size - check the exe size between last two releases) and the npm modules layout was better!. I think, its something to do with `npm 3`. I have  npm version `3.8.6`. 

Are you building against npm 2 ?  Have you tried running `npm dedupe` or fresh download (`rm -rf ./node_modules`)?

For time being, I'll add `babel-runtime` dependency! :smile:

**Comment by WolfieWerewolf** [comment]
Hey mate... I'm glad you weren't offended.. I actually depend on your 
tool every day I really should start contributing to your project.  I'm 
using npm 2.15.1 on OSX, maybe it's a mac thing.

Also there's bug with all the file related menus.  It complains about 
the title not being a string and then refused to display the dialog.. as 
a quick and dirty fixt I edited all the title properties in 
MenuManger.js just putting quotation markes around the item variable and 
that resovled it.  I don't know where item is coming from but calling 
toString() on it didn't work either...

Thanks mate.. again aweome work... I freaking love this thing.

/W

**Comment by princejwesley** [comment]
I am using mac for development. I have to update doc to enforce npm3 as build requirement. 

Regarding title issue,  It could be because of new electron version. I will update latest version  and will go through their change log.  :smile:

**Comment by princejwesley** [comment]
Thanks for reporting :smile:
