### ISSUE TITLE
Issues overriding existing function names (editing functions)

### ISSUE THREAD

**Issue by hph** [princejwesley/Mancy#138]
I run into the issue quite frequently that I've written a function which I want to edit. It's very convenient to be able to press the up arrow and get the whole definition again, but it doesn't seem to be very effective, as the new function body is completely ignored.
There are, of course, workarounds for this, like choosing a new name for the function or always assigning the function to a variable (`let func = function () { ... }`), but this is a bit inconvenient.

Would it be difficult to make new name definitions override the previous one, similar to what happens in a browser console?

Other than that, fantastic job with this program! It's much better than the default Node.js REPL and it seems to be the best one out there.

**Comment by princejwesley** [comment]
Duplicate #29 
Reason https://github.com/nodejs/node/issues/548

**Comment by hph** [comment]
Thanks @princejwesley, I've subscribed to the other issue.
