### ISSUE TITLE
Provide feedback for unsupported features/unexecutable code

### ISSUE THREAD

**Issue by jfsiii** [princejwesley/Mancy#14]
I can find no way to execute `const usesRest = (first, ...rest) => console.log(first, rest)` in Mancy.

Pressing `ENTER` behaves like `SHIFT+ENTER` (adds blank lines).

I looked for documentation on what features were supported (#13), but couldn't find any. I assume rest parameters are not supported because the line is evaluated if I replace `...rest` with `rest`.

There should be some feedback to the user. Either execute the code and throw a `SyntaxError`, or indicate that the code can't/won't be executed and list the reason.

**Comment by princejwesley** [comment]
@jfsiii Please make sure there is no typo in the command. Mancy delegates the request to node repl and if node responds saying continue the same command, you will see this behavior. 

For instance, if we type `x = { ` and enter, repl expects more input. Sometimes, we have to break the command (ctrl + c) if anything goes wrong.

Try the same command in node repl and check the behavior. In version 2, we will have babel support to prevent these errors.

**Comment by princejwesley** [comment]
@jfsiii Current electron backed node gives this output.

![image](https://cloud.githubusercontent.com/assets/1622515/10555539/2d54c5d8-748e-11e5-994b-20a2b98199a5.png)

**Comment by jfsiii** [comment]
@princejwesley There's not a typo, [it's valid code][babel_repl]

I assume it doesn't work because the feature isn't supported in the engine this uses, but that's only an assumption because there's no docs on engine or supported features (#13).

BTW, which node repl? Does Many have one or does it use the system node? Big feature differences between 0.10.x, 0.12.x & 4.x.

[babel_repl]: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=const%20usesRest%20%3D%20(first%2C%20...rest)%20%3D%3E%20console.log(first%2C%20rest)%3B%0A%0Aconsole.log(usesRest(1%2C2%2C3%2C4%2C5))

**Comment by princejwesley** [comment]
@jfsiii Yes. Mancy uses electron's node repl. This issue can be fixed if we treat all continuations as errors but only problem is, we have to use shift + enter always for multiple commands.

**Comment by princejwesley** [comment]
Fixed in version 2.

**Comment by princejwesley** [comment]
Merged to master
