### ISSUE TITLE
Mancyv2.2.2: cannot load javascript files with the word null

### ISSUE THREAD

**Issue by orionlee** [princejwesley/Mancy#148]
In Mancy v2.2.2, if I load a javascript file including the word null, such as the followingil
```
function bar() {
  var bar = null; 
   return bar;
}
```
The loading just failed and stopped silently.

The word null can even simply be in comment for the loading to fail:
```
function bar() {
  var bar = 123; // null; the loading still fails 
   return bar;
}
```

The problem no longer exists in v3.1.0,  v3.1.0 has a similar problem for another type of text (block comment in class functions. See #146.

Thanks.

**Comment by princejwesley** [comment]
👍
