### ISSUE TITLE
Async/await still fails with Babel and Auto async wrapper enabled 

### ISSUE THREAD

**Issue by jordansexton** [princejwesley/Mancy#153]
**Preferences**
<img width="470" alt="screen shot 2016-10-16 at 2 53 15 pm" src="https://cloud.githubusercontent.com/assets/1173161/19420462/67f31b3e-93b1-11e6-8290-cb2f90bf47dd.png">

**REPL**
<img width="1270" alt="screen shot 2016-10-16 at 3 00 07 pm" src="https://cloud.githubusercontent.com/assets/1173161/19420463/6e8d5fb8-93b1-11e6-9a0f-674a58f30035.png">

I tried many variations of these and other preferences, as well different attempts at wrapper constructs. Perhaps I'm doing something wrong, but `await` doesn't seem to work without constructing a wrapper yourself.

I read issues #71, #70, #63, and #26 in researching this. Is there something non-obvious about how this is supposed to work in Mancy?

**Comment by jordansexton** [comment]
**REPL**
<img width="1263" alt="screen shot 2016-10-16 at 3 06 58 pm" src="https://cloud.githubusercontent.com/assets/1173161/19420503/4b814808-93b2-11e6-8c81-7e379f0665b0.png">

Also tried wrapping the invocation in an `async` function (in case `await`ing a Promise itself is unsupported).

**Comment by GamerSolutions** [comment]
@jordansexton is it with master code or latest release? can you try master?

**Comment by jordansexton** [comment]
Thanks for the quick response! Latest npm release, I'll try master.

**Comment by GamerSolutions** [comment]
@jordansexton if I remember correctly, latest babel dependency expects some variation that has to be addressed. I mean https://github.com/princejwesley/Mancy/commit/6b0148bb3e7e40f3648791f18e46a211457efc62 one

**Comment by princejwesley** [comment]
@jordansexton if I remember correctly, latest babel dependency expects some variation that has to be addressed. I mean 6b0148b one

I should have raised a ticket and fixed it. I'll do that next time, very sorry! 😞

*edit*: previously replied from temp/someone's account.

**Comment by jordansexton** [comment]
That was it, works fine built from master. Thanks for your help and for all your work on this project!
