### ISSUE TITLE
Multiline code is evaluated multiple times

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#16]
Multiline code (shift+enter) is evaluated multiple times (as many as lines).

Example:
> 1+1;
2+2;
2

1+1;
2+2;
4

I think is not necessary Mancy show 1+1 result, only last line (2+2 = 4) that is the global result form entire input code,

**Comment by princejwesley** [comment]
Fixed in v2.

**Comment by princejwesley** [comment]
Merged to master
