### ISSUE TITLE
How are you using this in your normal development flow?

### ISSUE THREAD

**Issue by zeke** [princejwesley/Mancy#18]
Hello. I'm intrigued by this project. I just installed it and played around a bit. I see that it has some [nice features](https://github.com/princejwesley/Mancy#features) that you can't get from a regular node repl, but it's not immediately clear to me what I would use this tool for on day-to-day basis.

How are you using it?

**Comment by princejwesley** [comment]
@zeke Few thoughts: 
* Helps to learn javascript (for those who are new to js)
* Helps to test few lines of code or expression 
* We can try npm module before using it in code
* Trying new language features
