### ISSUE TITLE
Enhancement idea: automatically require core node modules

### ISSUE THREAD

**Issue by ccnokes** [princejwesley/Mancy#19]
Using the traditional node REPL from the terminal on Mac OS X, I don't have to `require` core node modules. For example:

```javascript
> os
{ hostname: [Function: getHostname],
  loadavg: [Function: getLoadAvg],
  uptime: [Function: getUptime],
  freemem: [Function: getFreeMem],
  totalmem: [Function: getTotalMem],
  cpus: [Function: getCPUs],
  type: [Function: getOSType],
  release: [Function: getOSRelease],
  networkInterfaces: [Function: getInterfaceAddresses],
  homedir: [Function: getHomeDirectory],
  arch: [Function],
  platform: [Function],
  tmpdir: [Function],
  tmpDir: [Function],
  getNetworkInterfaces: [Function: deprecated],
  EOL: '\n',
  endianness: [Function] }
```
But in Mancy that'll throw a ReferenceError. I've always liked that ability in the terminal because it allows for quickly iterating on something, which is what I use REPLs for. Mancy is cool, nice work :+1:

**Comment by princejwesley** [comment]
@ccnokes Yes. Its available in [version 2](https://github.com/princejwesley/Mancy/wiki/Features-&-Roadmap-for-version-2)

**Comment by princejwesley** [comment]
@ccnokes Its a bug, I missed to add os into context. Fix will be available in version 2.

**Comment by princejwesley** [comment]
Fix is available in v2 branch.

**Comment by princejwesley** [comment]
Merged to master
