### ISSUE TITLE
Window Resizing (OSX)

### ISSUE THREAD

**Issue by paradox41** [princejwesley/Mancy#22]
I don't seem to be able to resize the window past certain points. Please see attached gif.

OSX 10.10.5

![mancy](https://cloud.githubusercontent.com/assets/2791730/10700191/12721a94-798a-11e5-9e08-ddf9f629f3e2.gif)

**Comment by princejwesley** [comment]
@paradox41 I'll look into that. it could be electron bug.

**Comment by paradox41** [comment]
Great! Thanks for looking into it. If it is a bug with electron, I'm
willing to file it there as well.

**Comment by princejwesley** [comment]
@paradox41 Its not a electron bug. Fix will be available in v2 branch.

**Comment by paradox41** [comment]
Awesome. Thank you for the quick turn around.

**Comment by princejwesley** [comment]
Merged to master
