### ISSUE TITLE
Object output: show constructor name

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#24]
I know you can expand "Object" item and the expand "__proto__" item and then you have constructor name. But I think it would be useful look constructor name at first glance.

Example:
```javascript
class A {}
a = new A();
```
now you get:
```
> Object {}
```
I think it would be better something like this:
```
> Object (A) {}
```

Thank you.

**Comment by princejwesley** [comment]
Fixed in v2.

**Comment by princejwesley** [comment]
Merged to master
