### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#26]
[Babel transform: enabled]

Input:
```javascript
async function x() { return 100 }
await x()
```
Output: 
```
SyntaxError:  Unexpected token function
```
Expected output:
```
100
```

However if you code only this line:
```
async function x() { return 100 }
```
you get no error (right) and x() returns a promise (right).
Then, if you code this line: 
```
await x()
```
you get another promise (!) and it should return 100.

**Comment by princejwesley** [comment]
@pmros `async` auto wrapper for `awake` is handled for simple pattern as below:
```js
await expression
```
and it will transformed to 
```js
(async function() { let result = (await expression); return result; }())
```
If you feed expressions one after another, you will get expected result(pull latest code).

![image](https://cloud.githubusercontent.com/assets/1622515/10719404/4223d806-7bae-11e5-9ba9-db391f296bd1.png)

**Comment by pmros** [comment]
It would be nice if you could enable/disable await wrapper at preference panel.

**Comment by princejwesley** [comment]
@pmros In your case, it was not wrapped since its not a candidate for wrapping and `await` is not valid construct outside `async`.

**Comment by pmros** [comment]
I understand. What I was trying is something like this:
```javascript
(async function() {
async function xxx() { return 10 }
return await xxx();
})().then(x => console.log(x))
```
On [Tonic](https://tonicdev.com/) you get the same result just coding this:
```javascript
async function xxx() { return 10 }
await xxx();
```
I guess Tonic autowrap all your input code.

Whatever it's OK for me now I know how it works. Thank you.

**Comment by princejwesley** [comment]
@pmros I'll look into this approach of all `async` before v2 release. thanks

**Comment by princejwesley** [comment]
Contextify the wrapped calls is the challenge. Tonic has no such problem (I guess).

**Comment by princejwesley** [comment]
Merged to master
