### ISSUE TITLE
Don't use enter to autocomplete

### ISSUE THREAD

**Issue by patrickgaskill** [princejwesley/Mancy#30]
It's kind of a pain to evaluate short variables quickly since the autocomplete gets in the way. For example, I can't quickly type `n` and then hit enter, since it autocompletes to `new`. Considering that this is a REPL and you'd expect people to want to hit enter pretty often to evaluate things, doing autocomplete feels wrong to me.

**Comment by princejwesley** [comment]
@patrickgaskill I'll disable autocomplete selection on enter :+1:

**Comment by princejwesley** [comment]
Made it optional and turned off by default. (fixed in v2 branch)

**Comment by patrickgaskill** [comment]
Thanks!

**Comment by princejwesley** [comment]
Merged to master
