### ISSUE TITLE
OSX installation instructions not working

### ISSUE THREAD

**Issue by LeKeve** [princejwesley/Mancy#31]
Hello! Love the project. Just one issue I had so far:

Running `npm install` then `npm run package` does not initiate the application.

I had to run `gulp start` or `npm start`.

**Comment by natejlee** [comment]
I've had the same issue.

Needed to look through the gulp file to find proper gulp task to get the app running

**Comment by princejwesley** [comment]
@LeKeve @natejlee `npm run package` will build an executable and save it in `./dist` directory(for click & open). I'll update the documentation.

**Comment by princejwesley** [comment]
Merged to master
