### ISSUE TITLE
custom repl

### ISSUE THREAD

**Issue by boneskull** [princejwesley/Mancy#36]
I like what [n_](https://www.npmjs.com/package/n_) is doing.  Though this module likely is too specific to simply make a user preference, it'd be really swell if Mancy allowed you to wrap its REPL with a custom one.

Would this be possible?  Is this something you'd be interested in supporting?

Great work. :+1:

**Comment by boneskull** [comment]
(plugin support?)

**Comment by princejwesley** [comment]
@boneskull n_ - lodash plugin? I am not sure what it offers

**Comment by boneskull** [comment]
in node's REPL you are not allowed to assign a variable to `_`

n_ wraps the REPL so `_` becomes lodash.  

but this is just an example of a custom REPL.  for instance, [johnny-five](http://johnny-five.io) offers a custom REPL.  it'd be awesome if Mancy could support this sort of functionality.

**Comment by princejwesley** [comment]
@boneskull there is no special meaning for `_`(underscore) in Mancy `v2.0.0`. we can assign anything to it like lodash or underscore.js

**Comment by boneskull** [comment]
that's cool.
