### ISSUE TITLE
Support for history 

### ISSUE THREAD

**Issue by djds4rce** [princejwesley/Mancy#37]
Support for recalling old command execution. It would be better if the commands are stored in a file so that they can applied between sessions. Props for implementing Ctrl+R for searching through History.

**Comment by obvio171** [comment]
Crazy (?) idea: store history as a git repo, usinb libgit2. Single branch, append-only, one commit per command or output.

**Comment by princejwesley** [comment]
History navigation support is merged to master. History search development is in progress

![image](https://cloud.githubusercontent.com/assets/1622515/13591043/21b3b9b2-e50b-11e5-857f-aeb24a8cb42a.png)

**Comment by princejwesley** [comment]
History data is considered as part of auto completion result. Available in master branch
