### ISSUE TITLE
Requiring external node modules takes a very long time

### ISSUE THREAD

**Issue by djds4rce** [princejwesley/Mancy#38]
Not sure if this is a fixable issue but currently it takes a very long time to require external node modules.

**Comment by princejwesley** [comment]
@djds4rce we can add module paths either by `File -> Add module paths...`  or by setting `NODE_PATH`. Downloading module will happen only when there is no module with given name available in lookup path.

**Comment by princejwesley** [comment]
Building install/uninstall window will help.

**Comment by djds4rce** [comment]
I built the latest 2.0 build yesterday. Wont the NODE_ENV be picked up from my path?

**Comment by princejwesley** [comment]
@djds4rce  Added path in preferences for persistence
![image](https://cloud.githubusercontent.com/assets/1622515/11910257/285a762e-a619-11e5-941f-aa8ff578eda0.png)
