### ISSUE TITLE
Chart view works only for two and more collection.

### ISSUE THREAD

**Issue by xgrommx** [princejwesley/Mancy#39]
Hi @princejwesley. I tried to use smth like `let b = {x: [1,2,3,4,5]};` but for this one doesn't work a chart view. For `let b = {x: [1,2,3,4,5], y: [4,5,6,7,8]};` it's working correctly. Also I have another question about a prompt symbol. How can I change this one?

**Comment by princejwesley** [comment]
@xgrommx No provision to change the prompt symbol. Except active editing prompt, rest of the prompts are clickable actions to expand/collapse long commands.

Regarding chart, we need two fields at least to display it. if you want to see chart for single field **data**, you may have to cheat(:smile:) it by doing `let b = {x: [1,2,3,4,5], y:[]}`

![image](https://cloud.githubusercontent.com/assets/1622515/11017865/1e40d99a-85d4-11e5-8714-13b29ee47313.png)

**Comment by xgrommx** [comment]
@princejwesley I tried this trick but ok :smile_cat:

**Comment by princejwesley** [comment]
@xgrommx Enabled now :+1:
