### ISSUE TITLE
Clear screen shortcut

### ISSUE THREAD

**Issue by thesabbir** [princejwesley/Mancy#40]
In nodej.s REPL or bash we can use `Control + L' to clear the screen. I think it's missing from mancy :).

**Comment by princejwesley** [comment]
Clear all mapped to <kbd>cmd</kbd> + <kbd>k</kbd>(mac) or <kbd>ctrl</kbd> + <kbd>k</kbd>(win/linux). I'll remap to `L` in next release.

![image](https://cloud.githubusercontent.com/assets/1622515/11017814/49e8ce2e-85d2-11e5-8387-c0bfc3e8b86f.png)

![image](https://cloud.githubusercontent.com/assets/1622515/11017810/26e6d1b4-85d2-11e5-8e61-f801107200cd.png)
