### ISSUE TITLE
Build fails under npm v3

### ISSUE THREAD

**Issue by xgrommx** [princejwesley/Mancy#41]
@princejwesley I cannot rebuild Mancy on windows. I have errors about mime module.

**Comment by senthilporunan** [comment]
@xgrommx  can you give full error here.. For me it is working good in windows7 ..

**Comment by boneskull** [comment]
@xgrommx If you're using npm v3.x, try with v2.x instead.  This worked for me after having problems building on MacOS X.

**Comment by boneskull** [comment]
this ticket should be renamed; "Build fails under npm v3"

**Comment by princejwesley** [comment]
@xgrommx  [#43](https://github.com/princejwesley/Mancy/issues/43) PR helps ?

**Comment by xgrommx** [comment]
@princejwesley Looks like it's solved. Thanks

**Comment by xgrommx** [comment]
@princejwesley Another problem. After rebuild I don't have interface such on version 2.0.1. This is my result. But in dev mode it's working correctly.
![mancy - repl 0 2015-11-08 15 54 33](https://cloud.githubusercontent.com/assets/1499594/11020726/4b9246b0-8631-11e5-8f65-43d1f0610268.png)

**Comment by princejwesley** [comment]
@xgrommx let me try to reproduce it

**Comment by boneskull** [comment]
@princejwesley This is not unique to windows; I have the same problem *but only when running with npm v3*

**Comment by pmros** [comment]
Same problem here. But I'm using Linux.

I can run 
```
npm install
npm run package 
```
with no errors. Executable is generated at dist directory. But when I launch it, Mancy has no prompt (like xgrommx screenshot). However menu works (ie "About Mancy").

By the way, I uncommented [this line](https://github.com/princejwesley/Mancy/blob/master/gulpfile.babel.js#L262) and it worked OK (no crash). I use latest electron-prebuilt version (0.34.3).

**Comment by boneskull** [comment]
cursory test against `master` (as of this writing) under NodeJS v5.0.0 with npm v3.3.6 fails.

**Comment by boneskull** [comment]
best guess is that the code makes some assumptions about certain packages existing in `node_modules`, while npm v3 puts them somewhere else.

**Comment by princejwesley** [comment]
@xgrommx Tried against node `v5.0.0` and npm `v3.3.12` in OSX. No issues. let me try it in linux

**Comment by pmros** [comment]
node v5.0.0 and npm v3.3.12 in Linux (Arch Linux).

**Comment by boneskull** [comment]
@princejwesley did you `rm -rf node_modules` after switching versions?

**Comment by xgrommx** [comment]
@princejwesley I rebuild it again, doesn't work.

**Comment by princejwesley** [comment]
@boneskull No. I just gave npm install. let me try now.

**Comment by princejwesley** [comment]
@boneskull I can reproduce it. thanks.

**Comment by princejwesley** [comment]
Identified the issue. I'll fix and let you guys know

**Comment by princejwesley** [comment]
@boneskull @xgrommx @pmros npm 3 flattens the dependency structure. Fixed gulp task to handle it.

**Comment by pmros** [comment]
@princejwesley It work for me at Linux! So you could change note about Linux at README and add a Linux executable to next release (2.0.3). Good job! Thank you!

**Comment by princejwesley** [comment]
@pmros its not working for me (elementary OS 0.3.1 Freya). `rm -rf node_modules` and `npm install` might help. I'll try that.

**Comment by pmros** [comment]
This works for me:
```
cd dist/Mancy-linux-x64
./Mancy
```
But if I try to launch Mancy executable from another directory
```
./dist/Mancy-linux-x64/Mancy
```
I get a segmentation fault!

**Comment by princejwesley** [comment]
@xgrommx please confirm the fix

**Comment by princejwesley** [comment]
Closing it for now. Please feel free to open it if this issue is not resolved
