### ISSUE TITLE
Auto fill characters bug

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#48]
When you type '9', Mancy "autofill" another '9' character. I think it's a issue related to shift keycode and parentheses. When you type "(" or "(quotes), no autofill at all.

**Comment by princejwesley** [comment]
@pmros let me look into that

**Comment by princejwesley** [comment]
> When you type "(" or "(quotes), no autofill at all.
@pmros I don't understand this part.

**Comment by pmros** [comment]
I mean that if you type "[", Mancy autocomplete it with "]". If you type "{", Mancy autocomplete it with "}". But if you type "(", Mancy does not autocomplete it with ")", Mancy does not autocomplete. 

Sorry for my English. I hope you understand me. Thank you.

**Comment by princejwesley** [comment]
@pmros Please reopen this ticket if you can reproduce the issue in the latest build

**Comment by pmros** [comment]
When you write "?", Mancy show "??".

**Comment by princejwesley** [comment]
@pmros I am not able to reproduce this issue. let me try to reproduce it in my linux box

**Comment by pmros** [comment]
```
localectl status
```
```
   System Locale: LANG=es_ES.UTF-8
       VC Keymap: n/a
      X11 Layout: es
       X11 Model: pc104
```

**Comment by hugomrdias** [comment]
if i call a function auto-fill breaks with the parentheses

```
someFunction())
```

 the first closing parentheses doesnt autocomplete but when i manually type the first closing parentheses it adds another like the example above

**Comment by princejwesley** [comment]
@hugomrdias can you test in  `master` branch?

**Comment by hugomrdias** [comment]
npm install && npm run package

gives this error

```
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/home/hugomrdias/.nvm/versions/node/v5.4.0/bin/node" "/home/hugomrdias/.nvm/versions/node/v5.4.0/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.1.0 postinstall: `electron-rebuild && gulp clean && gulp copy`
npm ERR! Exit status 255
```

**Comment by princejwesley** [comment]
@hugomrdias  https://github.com/electronjs/electron-rebuild/issues/39 - related ?

**Comment by hugomrdias** [comment]
maybe im try now with node 0.12 npm 2

**Comment by hugomrdias** [comment]
worked and the problem is gone but there's no path completion now :/

**Comment by princejwesley** [comment]
@hugomrdias update preferences

**Comment by hugomrdias** [comment]
perfect @princejwesley release ETA ? :+1: just kidding 
thnx

**Comment by princejwesley** [comment]
@hugomrdias this weekend or monday :+1:
