### ISSUE TITLE
Application exe is crashing in linux

### ISSUE THREAD

**Issue by Norm-** [princejwesley/Mancy#6]
> Requiring external module babel-core/register
> Using gulpfile ~/JS/Mancy/gulpfile.babel.js
> Starting 'user-env'...
> Finished 'user-env' after 160 μs
> Starting 'start'...
> Starting 'build'...
> Starting 'clean'...
> Finished 'clean' after 224 ms
> Starting 'copy'...
> Finished 'copy' after 859 ms
> Starting 'sass'...
> Starting 'react'...
> Finished 'sass' after 2.62 s
> Finished 'react' after 4.87 s
> Finished 'build' after 6.14 s
> Starting 'run'...
> [5779:1012/214101:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

> Crash dump id: **9a459779-ccf5-4546-95d3-95e5d0b49ef1**

> Finished 'run' after 9.8 s
> Finished 'start' after 16 s

**Comment by princejwesley** [comment]
@Norm- can you confirm whether `gulp debug` works? I am facing segfault when built as an executable.

**Comment by Norm-** [comment]
It doesn't.

I got the same output as above only with a different ID.

I am guessing the answer is buried somewhere in that link.

**Comment by princejwesley** [comment]
@Norm- Please set  ` electron-prebuilt` version in `package.json` as `0.30.0` , give `npm update` and try.

**Comment by Norm-** [comment]
That worked.

I get the same error again but now the app launched.

> Starting 'run'...
> [13241:1012/231246:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

> [13267:1012/231247:INFO:renderer_main.cc(200)] Renderer process started

> [13241:1012/231248:INFO:CONSOLE(0)] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.", source:  (0)

> [13241:1012/231248:INFO:CONSOLE(0)] "'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.", source:  (0)

Thanks for the REPL, btw. I need something like the ipython notebook.

**Comment by princejwesley** [comment]
@Norm- yes, Hopefully in next version :+1:

**Comment by pmros** [comment]
I can do 'gulp start', 'gulp debug' and even 'npm dist' with no problems. I'm using Arch Linux and electron-prebuilt-0.34.3. So you can close this issue, if @Nom- is agree.

**Comment by pmros** [comment]
Application exe works for me only if I launch inside dist dir. I'm using Arch Linux.

This works for me:

cd dist/Mancy-linux-x64
./Mancy

But if I try to launch Mancy executable from another directory

./dist/Mancy-linux-x64/Mancy

I get a segmentation fault!

**Comment by princejwesley** [comment]
@pmros test against latest code.

**Comment by pmros** [comment]
Well sometimes... sometimes crash (segmentation fault), sometimes works! I'm gonna try electron 0.35.0 instead 0.34.3.

**Comment by pmros** [comment]
I've tried Mancy with electron 0.35.0. No crash. I've tried more than ten times and it worked OK all the time. You could update to electron 0.35.0, you had to fix a couple of deprecated warnings. I hope you could remove 😔 from README very soon.

**Comment by princejwesley** [comment]
V2.1.0 released. No crash encountered.

**Comment by chesstrian** [comment]
:+1:  Thanks
