### ISSUE TITLE
require(module) => Error: cannot find module

### ISSUE THREAD

**Issue by dylang** [princejwesley/Mancy#62]
This looks amazing, I look forward to using it more, but one of the basic features I'm not able to get working.

Whenever I tried to to `require` a module, I always get `Error: Cannot find module 'module-name'`.

![screen shot 2015-11-23 at 1 11 00 pm](https://cloud.githubusercontent.com/assets/51505/11345265/cc248aaa-91e3-11e5-81a1-51d6f755ea61.png)

It does work when I run from master locally, so it's possible this has already been addressed.

**Comment by princejwesley** [comment]
@dylang Are you getting this error in  [v0.2.1](https://github.com/princejwesley/Mancy/releases/tag/v2.0.1) ?

**Comment by dylang** [comment]
No, looks great! I could have sworn "latest release" pointed to 2.0.0 this morning, must have been user error. Thanks again for creating this!

**Comment by princejwesley** [comment]
thanks :smile:

**Comment by Leeds-eBooks** [comment]
I've got this problem too. Using v 2.1.0, OSX. Can I give you any other information that would be helpful? I downloaded the app from the releases page, and moved it to the Applications folder, and opened it. I previously had built my own from the repo which I cloned down to my machine, but I don't think that has anything to do with it? Thanks!

**Comment by princejwesley** [comment]
@Leeds-eBooks are you getting same error in v2.1.0 or in v2.0.1?

**Comment by Leeds-eBooks** [comment]
In 2.1.0, running the `.app` file on OSX (not `.exe`). Can you reproduce the error? If not I can try and provide you with more info.
