### ISSUE TITLE
Bug: Async/await returns promise object vs. resolved value

### ISSUE THREAD

**Issue by gnestor** [princejwesley/Mancy#63]
The value in the async/await pattern is that it allows us to work with async values like we would sync values vs. nesting callback or then blocks. Given that, thanks for adding this sugar to Mancy. However, these await statements return promise objects vs. the resolved values, so we still need to call then on them to access the resolved value.

#### Test: 

```javascript
let request = require('request-promise');
let todos = await request('http://jsonplaceholder.typicode.com/todos');
console.log(todos);
// Promise {}
// [[PromiseStatus]]: fulfilled
// [[PromiseValue]]:
// '[
//   {
//     "userId": 1,
//     "id": 1,
//     "title": "delectus aut autem",
//     "completed": false
//   }
//   ...
// ]'
todos.then(res => console.log(res));
// '[
//   {
//     "userId": 1,
//     "id": 1,
//     "title": "delectus aut autem",
//     "completed": false
//   }
//   ...
// ]'
```

Which ends up looking the same as a vanilla promise:

```javascript
let todos = request('http://jsonplaceholder.typicode.com/todos');
todos.then(res => console.log(res));
// '[
//   {
//     "userId": 1,
//     "id": 1,
//     "title": "delectus aut autem",
//     "completed": false
//   }
//   ...
// ]'
```

When I test this in my own environment using Babel and babel-preset-stage-0, it works, so I'm nor sure what the problem is...

**Comment by princejwesley** [comment]
@gnestor As you said, bare `await` is just a sugar. Therefore, what we get is a `async` function and `async` function returns a promise.

bare `await` transformation:
```js
(async function(){ let result = (await expression); return result; }())
let value = (async function(){ let result = (await expression); return result; }())
```
Try `master`(branch) which has support to view transpiled code 

![image](https://cloud.githubusercontent.com/assets/1622515/11431280/c3d7e778-94ba-11e5-8f18-704ceeae5cf4.png)

**Comment by princejwesley** [comment]
Tracked [here](https://github.com/princejwesley/Mancy/issues/71)
