### ISSUE TITLE
OSX: Clicking the Mancy icon in the dock bar (once it is running) invokes a new instance of Mancy

### ISSUE THREAD

**Issue by anami** [princejwesley/Mancy#66]
This issue is apparent on Macs.

Once Mancy is running, clicking the Mancy icon in the dockbar invokes a new instance of Mancy.
It may be engineered to behave this way but I feel users will find this confusing and disconcerting, I certainly did.

I'm running Mancy v2.1.0 on OSX El Capitan.  Using the release build of Mancy.

**Comment by kdabir** [comment]
+1
