### ISSUE TITLE
Is there anyway to automatically load a startup script when Mancy starts?

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#67]
First up. Mancy is awesome. I'm really loving it.

I'd like to have a startup script that loads all my most common modules and helper functions when I start Mancy.

Is it possible to do this already? Or are there any plans to implement this?

**Comment by princejwesley** [comment]
@ashleydavis Currently those npm modules downloaded from mancy(while giving require) will be available in node modules look up path. Other option is to NODE_PATH environment.

Similar ticket: [#38](https://github.com/princejwesley/Mancy/issues/38)

I'll add start up load path configuration in next version. I'll inform you once the code is merged to master.

**Comment by ashleydavis** [comment]
Thanks for your quick response.

I've already tried the feature where you can require a module and Mancy will automatically download the module. That's a really cool feature.

What I'm asking for is a little bit different. I want to load various modules to global variables and have the variables ready for use when I start using Mancy.

As an example...

I'm working on a data transformation toolkit called *data-forge*. It's going to be awesome to use it with Mancy.

When I start Mancy I currently have to do the following:

 var dataForge = require('data-forge');
 var csvPlugin = require('data-forge/format/csv');
 var filePlugin = require('data-forge/source/file');

I really want to move this to a startup script so that *dataForge* and the other variables are available to use as soon as Mancy has started.

**Comment by princejwesley** [comment]
@ashleydavis Make sense. I'll add it.
