### ISSUE TITLE
Table view for two dimensional data

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#69]
I like to implement a `toString` function for each my custom types, to be used to debug print the contents.

Does Mancy support, or are there any plans to support, implicit use of `toString` when outputting objects on the console?

**Comment by princejwesley** [comment]
@ashleydavis No plan for implicit `toString` output display. Current behaviour is consistent with chrome console output.

**Comment by ashleydavis** [comment]
Is there any way to customize the output for particular types/objects?

I noticed you can display graphs. Is there a way to make plugins for custom output?

**Comment by princejwesley** [comment]
@ashleydavis As of now, we don't have support for plugins. Do you want to see only the textual representation of custom object or the tree view as well?

**Comment by ashleydavis** [comment]
Have you seen *IPython notebook* and *Pandas*?

You can see it in this video: https://www.youtube.com/watch?v=rEalbu8UGeo

Start watching at 9 minutes to see how it renders data frames.

I'm building data-forge which is a data transformation and analysis toolkit inspired by Pandas. I want data-forge to work with Mancy the way that Pandas works with *IPython notebook*.

So I want to be able to render a *data frame* as a table in Mancy. But if you add support for custom/plugin visualisers then I could implement this myself.

I might be able to find time to help out on Mancy if you need more people working on it.

**Comment by princejwesley** [comment]
@ashleydavis I'll either add support for customized output plugin or customize your data frames exclusively. I'll get back to you. :+1:

**Comment by princejwesley** [comment]
@ashleydavis I don't think we need customizable output plugin.  All we need is a way to represent 2D data as table. Its easy to deduce 2D form and show as table.

**Comment by ashleydavis** [comment]
Sounds good. I'm still working on making data-forge easy to use from Mancy. When it's further advanced I'll yet you know so you can try it out.
