### ISSUE TITLE
Include some library to repl

### ISSUE THREAD

**Issue by xgrommx** [princejwesley/Mancy#7]
Hi @princejwesley. How can I include some library like a lodash to repl?

**Comment by princejwesley** [comment]
@xgrommx Use `File > Add module Path...` menu item to add lodash module path to REPL or set NODE_PATH env variable.

**Comment by xgrommx** [comment]
No, I want add it permanently =) @princejwesley

**Comment by princejwesley** [comment]
@xgrommx I'll add support for that and let you know :+1:

**Comment by maowug** [comment]
It would be perfect if it can be done like import from the REPL like 
`import "https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js"`

**Comment by princejwesley** [comment]
@maowug [Version 2 features](https://github.com/princejwesley/Mancy/wiki/Features-&-Roadmap-for-version-2) are completed. Its available in `v2` branch. 
You can do `require('lodash')` or any npm module to download to application's user data path.

```js
> let _ = require('lodash')
```

**Comment by maowug** [comment]
Great! :+1:

**Comment by princejwesley** [comment]
Merged to master

**Comment by xgrommx** [comment]
@princejwesley How about another think like a RxJS or smth like?

**Comment by princejwesley** [comment]
@xgrommx I am not sure what you are asking. loading reactive js?

**Comment by xgrommx** [comment]
@princejwesley now I can load `const _ = require('lodash')` but I also would like use Rx like so `const Rx = require('rx')`

**Comment by princejwesley** [comment]
@xgrommx  it will work in version 2.0.1.
![image](https://cloud.githubusercontent.com/assets/1622515/11015609/c25ae902-858a-11e5-929a-bf2f70cd73b8.png)

**Comment by xgrommx** [comment]
@princejwesley thanks!
