### ISSUE TITLE
Special support for promises?

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#70]
I noticed that Mancy already has *Auto async wrapper* and  *Promise output tracking*.

Would it be possibly to add an  *synchronous wrapper* for promises? 

Or does something like this already exist in Mancy?

Example...

The following code pulls json data from a REST API. Data-forge returns a promise that resolves when the async operation has completed:

 dataForge.from(http("some/rest/api")
     .as(json())
     .then(function (dataFrame)) {
         // ... do stuff with the data frame ...
     });

In Mancy I'd like this to behave like it was synchronous:

 var dataFrame = dataForge.from(http(...)).as(json());

Is it possible for Mancy to wrap promises automatically and then resolve them to their values?

**Comment by princejwesley** [comment]
bare `await` is not valid construct, and therefore, user can still reason about what is going on. User can turn on/off auto async wrapper as well. 

But here, the original input is a valid JS code. I don't want to surprise the user. Also, I want this tool to be used for learning purpose.

**Comment by ashleydavis** [comment]
Ok no probs. I'll implement `asyc` versions of the functions.
