### ISSUE TITLE
Does async/await work in Mancy?

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#71]
I assumed async/await works in Mancy after reading the wiki. But I'm having some problems with it.

I'm new to async/await, so I'm probably at fault here somehow.

I tried to get the following example into Mancy:

  async function getValues() {
      return [1,2,3,4];
  }

From this primer: http://code.tutsplus.com/tutorials/a-primer-on-es7-async-functions--cms-22367

I get this error:

  SyntaxError: Unexpected token function

I also tried the following alternatives which yield the same error:

  getValues = async function () { return [1,2,3,4]; }

  var getValues = async function () { return [1,2,3,4]; }

I also tried this alternative:

  let getValues = async function () { return [1,2,3,4]; }

Which gave this error:

  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Any ideas what's wrong here?

**Comment by princejwesley** [comment]
@ashleydavis Try with babel turned on.

**Comment by ashleydavis** [comment]
Cheers that allows me to define the `getValues` function.

How do I call the function?

This returns a promise.... as I expected:

  getValues();

This cause  the eror `SyntaxError: Unexpected identifier`:

  await getValues();

This causes the same error: 

  var a = await getValues()

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/11551251/95b8ab4c-999d-11e5-90e5-bd622cbeaaa4.png)

**Comment by princejwesley** [comment]
@ashleydavis [related](https://github.com/princejwesley/Mancy/issues/29)

**Comment by ashleydavis** [comment]
![image](https://cloud.githubusercontent.com/assets/625126/11551685/3760336a-99c7-11e5-9084-d150a862ad1c.png)

**Comment by ashleydavis** [comment]
I enabled *Auto async wrapper* and this works now:

![image](https://cloud.githubusercontent.com/assets/625126/11551715/8aac335c-99c7-11e5-975e-e9a47c4209f8.png)

It just doesn't work the way I expect.

![image](https://cloud.githubusercontent.com/assets/625126/11551735/a94f2e36-99c7-11e5-8663-295f908da528.png)

When I capture the results of `await getValues()` in `x` should the value be the promise? (as it is) Or should it be the resolved value of the promise?

I would have expected that the resolved value of the promise is extracted and stored in `x`.

**Comment by princejwesley** [comment]
```js
let x = await getValues();
```
wrapped as

```js
let x = (async function() { 
   let result = (await getValues());
   return result; 
}())
```
Only benefit of using bare `await` is to convert normal values to promise.

**Comment by ashleydavis** [comment]
What's the difference between these two lines of code:

  getValues();

  await getValues();

There doesn't seem to be any difference? If that's the case I don't understand the point of `await`.

I though it would resolve the promise and pull out the final value. Is that not the case?

**Comment by princejwesley** [comment]
`async` auto wrapper creates more confusion :disappointed: 
Yes, `await` resolves to value but its always wrapped inside `async`. I see `await` as a tool to treat async code **as** synchronous.

e.g.
```js
  async function fun() {
     let whatPromised = await somePromise();
     console.log(whatPromised);
  }
```
With `await`, we can treat `somePromise()` as synchronous call and print it in the next line. Here `fun()` is still async code. 

the above code roughly equivalent to
```js
  function fun() {
     return new Promise(function(resolve, reject) {
        try {
           getValues().then(function(whatPromised) {
               console.log(whatPromised);
               resolved();
           });
        } catch(e) {
           throw e;
        }
     });
  }
```
 
This is my understanding. Correct me if I am wrong.

**Comment by ashleydavis** [comment]
I'm just getting more confused :(

When I run the following two lines of code in Mancy, there doesn't seem to be any difference.

 getValues();

 await getValues();

**Comment by princejwesley** [comment]
@ashleydavis May be I can redefine the way wrapping async code and restrict the auto wrapping for `let variable = await expression` form. it will not be as confusing as in current form and you will get resolved value bound to desired variable.
