### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gbaumgart** [princejwesley/Mancy#72]
on the second ubuntu-x64 machine i get errors when installing:

npm http GET https://registry.npmjs.org/electron-packager/-/electron-packager-5.1.0.tgz
npm http 200 https://github.com/princejwesley/c3.git
npm http 200 https://registry.npmjs.org/font-awesome/-/font-awesome-4.5.0.tgz
npm ERR! not a package /home/mc009/tmp/npm-28860-luaTJ40S/1449359363038-0.886921145953238/tmp.tgz
npm ERR! Error: ENOENT, open '/home/mc009/tmp/npm-28860-luaTJ40S/1449359363038-0.886921145953238/package/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.13.0-68-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /PMaster/projects/Mancy
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path /home/mc009/tmp/npm-28860-luaTJ40S/1449359363038-0.886921145953238/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http 200 https://registry.npmjs.org/electron-prebuilt
npm http GET https://registry.npmjs.org/electron-prebuilt/-/electron-prebuilt-0.35.4.tgz
npm http 200 https://registry.npmjs.org/gulp-babel
npm http GET https://registry.npmjs.org/gulp-babel/-/gulp-babel-5.3.0.tgz
npm http 200 https://registry.npmjs.org/github/-/github-0.2.4.tgz
npm http 200 https://registry.npmjs.org/md5/-/md5-2.0.0.tgz
npm http 200 https://registry.npmjs.org/gulp-cached
npm http GET https://registry.npmjs.org/gulp-cached/-/gulp-cached-1.1.0.tgz
npm ERR! not a package /home/mc009/tmp/npm-28860-luaTJ40S/1449359363019-0.2757825730368495/tmp.tgz
npm http 200 https://registry.npmjs.org/reflux

is there a trick? i tried hard...
thanks!

**Comment by princejwesley** [comment]
@gbaumgart Try with node 4.x or 5.x.

**Comment by gbaumgart** [comment]
hi, so i did a nvm install v5.0.0 but it always gets stuck when compiling a native module: 

sudo npm install:

npm WARN cannot run in wd mancy@2.1.0 npm prune (wd=/install/Mancy)
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN engine jest-cli@0.5.10: wanted: {"node":">= 2"} (current: {"node":"0.12.7","npm":"2.11.3"})
 
> font-manager@0.1.0 install /install/Mancy/node_modules/font-manager
> node-gyp rebuild

make: Entering directory `/install/Mancy/node_modules/font-manager/build'
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
../src/FontManager.cc: In function ‘void asyncCallback(uv_work_t*)’:
../src/FontManager.cc:92:30: error: invalid conversion from ‘v8::Handle<v8::Value>*’ to ‘v8::Local<v8::Value>*’ [-fpermissive]
   req->callback->Call(1, info);
                              ^
In file included from ../src/FontManager.cc:5:0:
../node_modules/nan/nan.h:1421:3: error:   initializing argument 2 of ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ [-fpermissive]
   Call(int argc, v8::Local<v8::Value> argv[]) const {



i tried on 2 machines...

**Comment by princejwesley** [comment]
@gbaumgart  [node-gyp](https://github.com/nodejs/node-gyp#installation) instructions may help to build native modules.

> (current: {"node":"0.12.7","npm":"2.11.3"}) 
 Make sure node is 4.x or 5.x

**Comment by gbaumgart** [comment]
ok, got it! thank you. please mention this somewhere (most boxes are running 0.10-.0.12):

nvm install v5.0.0
nvm use v5.0.0 
npm install

g

**Comment by princejwesley** [comment]
@gbaumgart Sure, I'll update it
