### ISSUE TITLE
Auto-fill + entering character / Optional to turn this off

### ISSUE THREAD

**Issue by marclemagne** [princejwesley/Mancy#74]
I have seen it in editors where, for example, if you type an "(" it will auto-fill an ")" and it's cool that Mancy does this, as well. The problem I am seeing is that if I then type that ")" myself, it will add another ")" instead of replacing that auto-filled ")"--like many other editors do.

So you end up with: `something())` instead of the expected `something()`.

It would also be nice to be able to turn auto-fill off completely.

**Comment by princejwesley** [comment]
@marclemagne sure thing.

**Comment by pmros** [comment]
Related to issue #48.
Consider use editor components like Ace, it feature autofill, bracket matching and another niceties.

**Comment by princejwesley** [comment]
@pmros let me check those. we need external auto-completion support as well

**Comment by pmros** [comment]
@princejwesley these libraries ussually let some developer customizations (hooks, callbacks, events, etc.)

**Comment by princejwesley** [comment]
@pmros :+1:

**Comment by princejwesley** [comment]
@pmros ace is BCD licensed. code mirror seems good.

**Comment by pmros** [comment]
@princejwesley Code mirror is good for me :+1:

**Comment by marclemagne** [comment]
Wow, you guys are awesome! Thanks!
