### ISSUE TITLE
Should be able to select and run arbitrary JavaScript code in Mancy

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#75]
It'd be nice if you could select and then run JavaScript files in Mancy.

I'm talking about a *Run Script* menu item under the *File* menu. This should bring up an open file dialog to allow you to select a Javascript file to run.

Mancy should remember Javascript files that have been recently executed. It should be possible to rerun recent scripts from a *recently used file menu*.

**Comment by princejwesley** [comment]
@ashleydavis time being use `.load absolute-file-name` to load file.

**Comment by ashleydavis** [comment]
Thanks!
