### ISSUE TITLE
Should be able to save previously entered commands as a Javascript file

### ISSUE THREAD

**Issue by ashleydavis** [princejwesley/Mancy#76]
I like to use Mancy to build code as I explore data. 

A menu to save the command history as a plain Javascript file would be great. That would make an easy way to transition from running code in Mancy (where I like to start coding) to running code under NodeJS (where I end up once the exploratory coding phase is over).

**Comment by princejwesley** [comment]
@ashleydavis  `save as` option with successfully executed commands ?

**Comment by princejwesley** [comment]
`Save as ...` feature has a drawback which is worth mentioning here. Mancy supports coffee, typescripts as well. Mancy uses one context per window and therefore shares it across languages. 

We can write one function in one language and execute it in another. therefore, the exported file may have mix of `js/coffee/typescript`.

**Comment by ashleydavis** [comment]
That's ok.

The user has to now what language they are working in. If they mix those languages they should expect the 'command history' to be saved out as multi-language.

**Comment by princejwesley** [comment]
@ashleydavis My comment is for the record :smile:
