### ISSUE TITLE
Add: A hot key to enter edit mode and go to the last edit line maybe is nice

### ISSUE THREAD

**Issue by Honghe** [princejwesley/Mancy#77]
At present, we have to click the right input line via mouse to go to and edit it, this is a bit of inefficient.
Maybe can add a hot key to quickly focus the last edit line and enter edit mode(e.g. `esc` key), just like `Jupyter notebook`. :smiley:

**Comment by princejwesley** [comment]
Shortcuts  <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>0..9</kbd> binds to last 10 commands.
(e.g)
To edit ultimate command,  press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>0</kbd>.
To edit penulitmate command,  press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>1</kbd>.
