### ISSUE TITLE
Missing angle brackets when copy-pasting functions with generics in TypeScript

### ISSUE THREAD

**Issue by fllstck** [princejwesley/Mancy#80]
Consider the following typescript function with a `<T>` generic variable.
```TypeScript
function firstHalf<T>(xs: T[]): T[] {
    let halfLength = xs.length / 2;
    return xs.slice(0, halfLength);
}
```

Whenever I copy-paste this example into the Mancy repl, the angle brackets `<T>` disappear. This results in a type error being reported.

![screenshot 2015-12-18 20 29 22](https://cloud.githubusercontent.com/assets/1329167/11910503/156b2b56-a5c6-11e5-8115-ce7c127436fa.png)

**Comment by princejwesley** [comment]
@fllstck Fixed.
![image](https://cloud.githubusercontent.com/assets/1622515/11910547/23ead8da-a61f-11e5-8831-2eeaf7ed7c2f.png)

**Comment by fllstck** [comment]
Looks good to me!
