### ISSUE TITLE
Ability to disable auto-closing characters

### ISSUE THREAD

**Issue by joshq00** [princejwesley/Mancy#81]
When I type `[`, Mancy will automatically add a `]`.
I would like a way to disable this.

For example, when I type `['a','b','c']`, I end up with `['a','b','c']'''''']`
It's easier for me to type `['a','b','c']` than it is to do `['a→,'b→,'c→→`

I would consider leaving it enabled if it could intelligently recognize when I'm typing a character it has already auto-closed and not duplicate. But, in general, it would be nice to disable.

**Comment by princejwesley** [comment]
[master](https://github.com/princejwesley/Mancy/commit/e61265a4f4e6bb945bf421e74de91e016154439b) branch has preference to disable it. 

![image](https://cloud.githubusercontent.com/assets/1622515/11911711/b552a922-a644-11e5-8377-a088c3b4f921.png)

I'll fix this use case before 2.2 release.

**Comment by joshq00** [comment]
:shipit: thank you for the useful app!
