### ISSUE TITLE
"Missing catch or finally after try"

### ISSUE THREAD

**Issue by AriaFallah** [princejwesley/Mancy#84]
Here's the code:

```javascript
function thunkify(fn) {
  return function() {
    var args = new Array(arguments.length);
    var ctx = this;

    for (var i = 0; i < args.length; ++i) {
      args[i] = arguments[i];
    }

    return function(done) {
      var called;

      args.push(function() {
        if (called) return;
        called = true;
        done.apply(null, arguments);
      });

      try {
        fn.apply(ctx, args);
      } catch (err) {
        done(err);
      }
    }
  }
};
```

Which is from [here](https://github.com/tj/node-thunkify/blob/master/index.js)

It runs fine in the chrome console

**Comment by princejwesley** [comment]
@AriaFallah  Are you getting "Missing catch or finally after try" error? 
![image](https://cloud.githubusercontent.com/assets/1622515/12127584/1976a37c-b41e-11e5-8bd9-a490b0ff05fe.png)

**Comment by AriaFallah** [comment]
Yep.

![screen shot 2016-01-05 at 4 15 49 pm](https://cloud.githubusercontent.com/assets/9424976/12127847/96fdc336-b3c7-11e5-98f6-0835cd1fa5ef.png)

**Comment by princejwesley** [comment]
@AriaFallah can you share the stack trace and preference settings to reproduce this issue? can you able to reproduce the same in `master` ?

**Comment by AriaFallah** [comment]
Here are the stack trace and preferences.

![screen shot 2016-01-05 at 4 24 27 pm](https://cloud.githubusercontent.com/assets/9424976/12128039/d0238956-b3c8-11e5-9f42-4b70bfce9656.png)
![screen shot 2016-01-05 at 4 24 58 pm](https://cloud.githubusercontent.com/assets/9424976/12128052/e3b68568-b3c8-11e5-80ce-32dd1e2327ef.png)

I haven't tried master.

**Comment by princejwesley** [comment]
@AriaFallah Yes, turn off babel for time being and try. `master` branch is working fine.

**Comment by AriaFallah** [comment]
Yep it works without babel.

**Comment by princejwesley** [comment]
@AriaFallah  With babel-transform, input is transformed as below before invoking node REPL API.

```js
function thunkify(fn) {
  return function () {
    var args = new Array(arguments.length);
    var ctx = this;

    for (var i = 0; i < args.length; ++i) {
      args[i] = arguments[i];}


    return function (done) {
      var called;

      args.push(function () {
        if (called) return;
        called = true;
        done.apply(null, arguments);});


      try {
        fn.apply(ctx, args);} 
      catch (err) {
        done(err);}};};}



;
```
If you paste the same in node repl, you can get the same error.
![image](https://cloud.githubusercontent.com/assets/1622515/12128642/9ab854de-b424-11e5-8242-23db5c029b9f.png)

### Conclusion 
Node REPL has issues handling multiline commands.

![image](https://cloud.githubusercontent.com/assets/1622515/12128768/782a02ea-b425-11e5-8747-2c585661684c.png)

Upcoming version solves these issues by limiting the use of node REPL API (used only for auto completion & load file) :+1: .
