### ISSUE TITLE
--startup script option support

### ISSUE THREAD

**Issue by neouser99** [princejwesley/Mancy#86]
Nice project so far, keep up the good work!

It's possible to programmatically create a node repl server, which gives you the ability to add things to the running context. This is slightly different than just module loading. For instance, it would be nice if I could wire up a database context, and run a query, then load that information into the mancy context which is available straight away for auto-complete or whatever else is necessary.

Is this possible? Sorry if it is already and I missed it...

**Comment by princejwesley** [comment]
@neouser99  load your script either as `startup script` from `preference` window (if you want it every time) or using `File` -> `Load File...` option

![image](https://cloud.githubusercontent.com/assets/1622515/12397321/823f0f0c-be32-11e5-874e-a27c2dc27b9c.png)

**Comment by neouser99** [comment]
So.. anything I add to 'global' from that script will be available? I guess
maybe I'm not 100% sure how that part works.

Also, it'd be nice if this could be done on launch. I'd like to have a gulp
command launch mancy, running given script. This script isn't something I
necessarily want to run all the time.

**Comment by princejwesley** [comment]
> So.. anything I add to 'global' from that script will be available? I guess
maybe I'm not 100% sure how that part works.

Yes, Mancy REPL creates a context per window which acts as global. Just like node's repl, `global` and `root` aliases refers to the global context.

>Also, it'd be nice if this could be done on launch. I'd like to have a gulp
command launch mancy, running given script. This script isn't something I
necessarily want to run all the time.

Use `preferences/Startup script` to configure which file to load on launch(script should be written in one of the supporting languages)

**Comment by neouser99** [comment]
OK, that makes sense for the for modifying the global/context variables,
thanks for that information.

I think I might not be explaining the second piece correctly. Basically,
it'd be cool if we could have different Mancy environments. I don't want
this startup script I'm talking about to run every time I run Mancy. I'd
like it to only run in certain instances, i.e. when I launch Mancy from
within a project I'm writing. If I run Mancy outside of this project, like
just from my dock, I would not want this script to run. I'm thinking
something like: mancy --startup path/to/script

**Comment by princejwesley** [comment]
@neouser99 let me add it as feature for next release. I'll let you know once its merged to master. :+1:

**Comment by neouser99** [comment]
Cool, that's awesome! If I find some personal time soon, I'll attempt a
pull request if it hasn't been done already.

**Comment by princejwesley** [comment]
:+1:

**Comment by princejwesley** [comment]
Process options:

```markdown
-s | --script   script file to load
-m | --mode     REPL mode (applicable only for JS).
                (**Allowed values**: 'magic', 'sloppy' or 'strict')
-e | --editor   REPL or Notebook(experimental) mode
                (**Allowed values**: 'repl', or 'notebook')
-t | --theme    Editor theme.
                (**Allowed values**: 'dark', or 'white')
-l | -lang      scripting language. (**Allowed values**: 'js', 'javascript', 'ts',
                'typescript', 'ls', 'livescript', 'coffee', 'coffeescript')


```
