### ISSUE TITLE
Interesting half-working babel-6 situation

### ISSUE THREAD

**Issue by krainboltgreene** [princejwesley/Mancy#89]
<img width="1003" alt="screen shot 2016-01-18 at 4 35 50 pm" src="https://cloud.githubusercontent.com/assets/334809/12406422/abc95462-be01-11e5-9237-4bf60fb0b9c3.png">

**Comment by princejwesley** [comment]
@krainboltgreene interesting!
![image](https://cloud.githubusercontent.com/assets/1622515/12406497/857d2a28-be73-11e5-822b-9c3f27646e39.png)

**Comment by princejwesley** [comment]
@krainboltgreene same behaviour in `babel 5`.

![image](https://cloud.githubusercontent.com/assets/1622515/12406545/fa344c66-be73-11e5-856b-5d2962be2d01.png)

**Comment by krainboltgreene** [comment]
Okay, that totally makes sense. I assumed mancy from the terminal would use my babel setup.

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/12406712/985fa4c0-be75-11e5-80e0-db3d5c0e6920.png)

**Comment by princejwesley** [comment]
@krainboltgreene I'll reopen this ticket to address the below transformation

Transform
```js
import {x,y,z} from 'module'
```
to
```js
import {x,y,z} from 'module';
context.x = _.module.x;
context.y = _.module.y;
context.z = _.module.z;
```

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/12407832/d6030f28-be80-11e5-97c7-3776898927be.png)

**Comment by krainboltgreene** [comment]
Nice!
