### ISSUE TITLE
Secure sandbox (while(true){})

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#9]
Hi!
I'm thinking about create a Node REPL based on Electron and I've found Mancy! Great job! Very very nice!
I don't know yet how Mancy eval/run input code but I've tried this code
```javascript
while(true){}
```
and Mancy hangs completely (Node CLI REPL hangs too). But it would be nice if you could stop/cancel the last execution (infinite loop in this case) and continue working with Mancy. I think Mancy would need to execute input code at another process (child). Parent process (global data) and child process (execution) would have to communicate in order to share global data. So you could kill child process if it hangs and continue working whith Mancy and your current session (global data).
Thank you for Mancy! Go on!

**Comment by princejwesley** [comment]
:+1:  I'll fix in next release.

**Comment by princejwesley** [comment]
@pmros Thanks for your valuable comments :ok_hand:

**Comment by princejwesley** [comment]
Fixed in version 2

**Comment by princejwesley** [comment]
Merged to master
