### ISSUE TITLE
CoffeeScript: Reserved Word 'Void'

### ISSUE THREAD

**Issue by 9000-volts** [princejwesley/Mancy#95]
CoffeeScript does not work with Mancy unless I move out of `strict` mode. I get the error `reserved word 'void'`.
![Animated Screenshot](https://cloud.githubusercontent.com/assets/1672106/12659489/0ca256a2-c5dd-11e5-935b-11a17bacf163.gif)
I am using windows 10, node v0.12.7.

**Comment by princejwesley** [comment]
@9000-volts I haven't closed this issue. looks like new github feature. Feel free to reopen it if the issue still persists.

**Comment by 9000-volts** [comment]
@princejwesley I'll have to clone the repo and check if it persists.
Amazingly quick response, though! :smile:

**Comment by princejwesley** [comment]
@9000-volts 
[auto issue close](https://help.github.com/articles/closing-issues-via-commit-messages/) - I used one of the reserved words along with issue id in my commit which triggers auto close.
