### ISSUE TITLE
Object.prototype.isPrototypeOf returns false for object literals

### ISSUE THREAD

**Issue by feimosi** [princejwesley/Mancy#96]
Not a big issue, but I've just noticed that:
``` js
a = {}
Object.prototype.isPrototypeOf(a) // returns false
```
and
``` js
a = new Object()
Object.prototype.isPrototypeOf(a) // returns true
```
Of course in both cases it should be true. I've checked that on Node and Chrome. Works good on both.
Mancy v2.2.0

**Comment by princejwesley** [comment]
@feimosi  Issue is in [script.runInContext](https://nodejs.org/dist/latest-v5.x/docs/api/vm.html#vm_script_runincontext_contextifiedsandbox_options) function.  node repl runs in `global` context(`script.runInThisContext`) and therefore, it works.  I see few [open issues](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Avm) reported in node repo. Its a v8 issue. node or v8 repo is a ideal place to raise this.
<img width="1389" alt="screen shot 2016-01-29 at 9 30 31 pm" src="https://cloud.githubusercontent.com/assets/1622515/12680489/2ef0ae9a-c6d0-11e5-88c4-20cbb600aef8.png">
![screen shot 2016-01-29 at 9 30 19 pm](https://cloud.githubusercontent.com/assets/1622515/12680491/33815824-c6d0-11e5-98d4-d6e5c8505cd0.png)

**Comment by princejwesley** [comment]
@feimosi I raised [related issue](https://github.com/nodejs/node/issues/3158) few months ago. root cause sounds [similar](https://github.com/nodejs/node/issues/3158#issuecomment-144977632)

**Comment by feimosi** [comment]
@princejwesley Thanks for the quick response. You're right, it's a node related issue, let's wait for the fix then.

**Comment by princejwesley** [comment]
@feimosi Its not a node issue. I'll work on the fix.

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/12864163/c5c77cb2-cca8-11e5-9c63-0ef30e749004.png)

**Comment by feimosi** [comment]
Great, thanks for the fix! So we can consider this issue as resolved.
