### ISSUE TITLE
can not install 2.2.1

### ISSUE THREAD

**Issue by xieyuheng** [princejwesley/Mancy#97]
1  ~/download/Mancy-2.2.1 
npm i    
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
npm WARN prefer global npm@3.7.2 should be installed with -g
npm WARN prefer global cover@0.2.9 should be installed with -g
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> nslog@3.0.0 install /home/xyh/download/Mancy-2.2.1/node_modules/nslog
> node-gyp rebuild

make: Entering directory '/home/xyh/download/Mancy-2.2.1/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_linux.o
  SOLINK_MODULE(target) Release/obj.target/nslog.node
  COPY Release/nslog.node
make: Leaving directory '/home/xyh/download/Mancy-2.2.1/node_modules/nslog/build'

> node-sass@3.4.2 install /home/xyh/download/Mancy-2.2.1/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/xyh/download/Mancy-2.2.1/node_modules/node-sass/vendor/linux-x64-47/binding.node

> font-manager@0.2.0 install /home/xyh/download/Mancy-2.2.1/node_modules/font-manager
> node-gyp rebuild

make: Entering directory '/home/xyh/download/Mancy-2.2.1/node_modules/font-manager/build'
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
  CXX(target) Release/obj.target/fontmanager/src/FontManagerLinux.o
  SOLINK_MODULE(target) Release/obj.target/fontmanager.node
  COPY Release/fontmanager.node
make: Leaving directory '/home/xyh/download/Mancy-2.2.1/node_modules/font-manager/build'

> spawn-sync@1.0.15 postinstall /home/xyh/download/Mancy-2.2.1/node_modules/spawn-sync
> node postinstall

> node-sass@3.4.2 postinstall /home/xyh/download/Mancy-2.2.1/node_modules/node-sass
> node scripts/build.js

` /home/xyh/download/Mancy-2.2.1/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> electron-prebuilt@0.36.7 postinstall /home/xyh/download/Mancy-2.2.1/node_modules/electron-prebuilt
> node install.js

> mancy@2.2.1 preinstall /home/xyh/download/Mancy-2.2.1
> npm prune

> mancy@2.2.1 postinstall /home/xyh/download/Mancy-2.2.1
> electron-rebuild && gulp clean && gulp copy

[02:01:54] Requiring external module babel-register
/home/xyh/download/Mancy-2.2.1/gulpfile.babel.js:4
  var ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(api) {
                              ^

ReferenceError: regeneratorRuntime is not defined
    at /home/xyh/download/Mancy-2.2.1/gulpfile.babel.js:4:31
    at Object.<anonymous> (gulpfile.babel.js:65:16)
    at Module._compile (module.js:413:34)
    at loader (/home/xyh/download/Mancy-2.2.1/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/xyh/download/Mancy-2.2.1/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/home/xyh/download/Mancy-2.2.1/node_modules/gulp/bin/gulp.js:116:3)

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/usr/bin/node" "/home/xyh/.npm-installed/bin/npm" "i"
npm ERR! node v5.6.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.2.1 postinstall: `electron-rebuild && gulp clean && gulp copy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mancy@2.2.1 postinstall script 'electron-rebuild && gulp clean && gulp copy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mancy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild && gulp clean && gulp copy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mancy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mancy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xyh/download/Mancy-2.2.1/npm-debug.log

1  ~/download/Mancy-2.2.1

**Comment by princejwesley** [comment]
@xieyuheng can you confirm the below npm packages are installed successfully ?
``` json
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-plugin-add-module-exports": "^0.1.1",
    "babel-plugin-transform-runtime": "^6.3.13",
    "babel-core": "^6.3.13",
    "babel-polyfill": "^6.3.14",
    "babel-runtime": "^6.3.13",
```

**Comment by xieyuheng** [comment]
I tryed it with another version of npm it stoped here as following ::

  ~/download/kkkk/Mancy-2.2.1 
cnpm i          

> mancy@2.2.1 preinstall /home/xyh/download/kkkk/Mancy-2.2.1
> npm prune

npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
 
> font-manager@0.2.0 install /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/font-manager
> node-gyp rebuild

make: Entering directory '/home/xyh/download/kkkk/Mancy-2.2.1/node_modules/font-manager/build'
  CXX(target) Release/obj.target/fontmanager/src/FontManager.o
  CXX(target) Release/obj.target/fontmanager/src/FontManagerLinux.o
  SOLINK_MODULE(target) Release/obj.target/fontmanager.node
  COPY Release/fontmanager.node
make: Leaving directory '/home/xyh/download/kkkk/Mancy-2.2.1/node_modules/font-manager/build'
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
 
> nslog@3.0.0 install /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

make: Entering directory '/home/xyh/download/kkkk/Mancy-2.2.1/node_modules/electron-rebuild/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_linux.o
  SOLINK_MODULE(target) Release/obj.target/nslog.node
  COPY Release/nslog.node
make: Leaving directory '/home/xyh/download/kkkk/Mancy-2.2.1/node_modules/electron-rebuild/node_modules/nslog/build'
-
> electron-prebuilt@0.36.7 postinstall /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/electron-prebuilt
> node install.js

 
> spawn-sync@1.0.15 postinstall /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

|
> node-sass@3.4.2 install /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/node-sass/vendor/linux-x64-47/binding.node

> node-sass@3.4.2 postinstall /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/node-sass
> node scripts/build.js

` /home/xyh/download/kkkk/Mancy-2.2.1/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> mancy@2.2.1 postinstall /home/xyh/download/kkkk/Mancy-2.2.1
> electron-rebuild && gulp clean && gulp copy

[02:32:08] Requiring external module babel-core/register
[02:32:44] Using gulpfile ~/download/kkkk/Mancy-2.2.1/gulpfile.babel.js
[02:32:44] Starting 'clean'...
[02:32:44] Finished 'clean' after 124 ms
[02:32:46] Requiring external module babel-core/register
[02:33:19] Using gulpfile ~/download/kkkk/Mancy-2.2.1/gulpfile.babel.js
[02:33:19] Starting 'watchableCopy'...
[02:33:20] Finished 'watchableCopy' after 787 ms
[02:33:20] Starting 'copy'...

**Comment by xieyuheng** [comment]
I also tryed Mancy-linux-x64.zip here :: https://github.com/princejwesley/Mancy/releases/tag/v2.2.1

but nothing happened when I open ./Mancy

**Comment by princejwesley** [comment]
@xieyuheng Yes, run `npm run package` after `npm install` and run from `dist` directory

If you don't want to build from source, try `npm install -g mancy`

**Comment by xieyuheng** [comment]
I also tryed npm install -g mancy
but after I open mancy
I can not see the window (even after a long time)
my friend is meeting the same problem as me

thanks for your reply
I am trying to test more

**Comment by princejwesley** [comment]
@xieyuheng let me check from my linux box.

**Comment by xieyuheng** [comment]
thanks :)
I really wish to be able to use mancy

**Comment by princejwesley** [comment]
@xieyuheng prebuilt exe has issues. Try `npm install` and wait till `Starting 'copy'...` task is completed. Run `npm run package` and run ./dist/Mancy-linux-x64/Mancy` from `/home/xyh/download/Mancy-2.2.1/`

I'll fix the executable and upload it.

**Comment by xieyuheng** [comment]
oh I will try the previous version first

**Comment by xieyuheng** [comment]
I can run 2.1.0 
but in 2.2.0 I meet the same problem

I will use 2.1.0 for now 
thanks

**Comment by princejwesley** [comment]
@xieyuheng Updated executable for linux 64bit.

**Comment by xieyuheng** [comment]
thanks again
